# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

workspace 'SmartJSWebViewDemo.xcworkspace'
project 'SmartJSWebViewDemo.xcodeproj'

target 'SmartJSWebViewDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SmartJSWebViewDemo
  pod 'SmartJSWebView'
  pod 'Toast'
end
